#!/usr/bin/env python3
"""Check that every `sc_goal` label pairs with a generated `sc_justify` label.

`sc_goal` labels are hand-written in the per-mod catalog; `sc_justify` labels
are generated by `core/tools/extract_arc_hooks.py` from the same catalog and
are always lowercase. If the two drift apart, one arc pair reads as two
different keys when a session log is grepped (issue 05).

This checks, per mod:
  * no `sc_goal` / `sc_justify` label carries uppercase;
  * no label uses a tag the mod does not have (`ROU` is not a tag here; Romania
    is `ROM`);
  * every forward pair derived from `sandbox_set_targets()` x
    `sandbox_seed_actors()` (aggressor -> target) appears in both streams.

`sc_goal` legitimately logs both directions, so a `sc_goal`-only label is fine
as long as it is the reverse of a forward pair; `sc_justify` is aggressor-only.

Usage:
  python check_sc_labels.py [mod_dir ...]

With no arguments it checks the two mod folders on this machine.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

DEFAULT_MODS = [
    Path.home() / "Documents/Paradox Interactive/Hearts of Iron IV/mod/_sandbox",
    Path.home() / "Documents/Paradox Interactive/Hearts of Iron IV/mod/_sandbox-r56",
]

CATALOG_REL = "common/scripted_effects/99_sandbox_scenarios.hsl"
HOOKS_REL = "common/scripted_effects/99_sandbox_arc_hooks.hsl"

GOAL_RE = re.compile(r"sc_goal,\s*([A-Za-z0-9_]+)")
JUSTIFY_RE = re.compile(r"sc_justify,\s*([A-Za-z0-9_]+)")
FUNC_RE = re.compile(r"^([A-Za-z_0-9]+)\(\):$")
ARC_RE = re.compile(r"^\s*(?:if|elif) global\.sandbox_scenario == (\d+):\s*$")
VAR_RE = re.compile(r"^\s*if global\.sandbox_target_variant == (\w+):\s*$")
ELSE_RE = re.compile(r"^\s*else:\s*$")
ADD_RE = re.compile(r"^\s*global\.&sandbox_targets\[\]\.add\((\w+)\)\s*$")
TAG_RE = re.compile(r"^\s*([A-Z]{3}):\s*$")


def split_functions(lines: list[str]) -> dict[str, list[str]]:
    funcs: dict[str, list[str]] = {}
    cur: str | None = None
    for line in lines:
        m = FUNC_RE.match(line)
        if m:
            cur = m.group(1)
            funcs[cur] = []
        elif cur is not None:
            funcs[cur].append(line)
    return funcs


def forward_pairs(catalog: Path) -> set[str]:
    """Aggressor -> target labels implied by the catalog's own arc tables."""
    funcs = split_functions(catalog.read_text(encoding="utf-8").splitlines())
    for name in ("sandbox_set_targets", "sandbox_seed_actors"):
        if name not in funcs:
            raise SystemExit(f"error: {catalog} has no {name}()")

    targets: dict[int, dict[str, list[str]]] = {}
    arc: int | None = None
    variant: str | None = None
    for line in funcs["sandbox_set_targets"]:
        m = ARC_RE.match(line)
        if m:
            arc = int(m.group(1))
            targets[arc] = {}
            variant = None
            continue
        if arc is None:
            continue
        m = VAR_RE.match(line)
        if m:
            variant = m.group(1)
            targets[arc].setdefault(variant, [])
            continue
        if ELSE_RE.match(line):
            variant = "b"
            targets[arc].setdefault(variant, [])
            continue
        m = ADD_RE.match(line)
        if m and variant:
            targets[arc][variant].append(m.group(1))

    aggressors: dict[int, str] = {}
    arc = None
    for line in funcs["sandbox_seed_actors"]:
        m = ARC_RE.match(line)
        if m:
            arc = int(m.group(1))
            continue
        m = TAG_RE.match(line)
        if m and arc is not None:
            aggressors[arc] = m.group(1)

    pairs: set[str] = set()
    for a, variants in targets.items():
        agg = aggressors.get(a)
        if not agg:
            continue
        for tags in variants.values():
            for tgt in tags:
                pairs.add(f"{agg.lower()}_on_{tgt.lower()}")
    return pairs


def check(mod: Path) -> list[str]:
    catalog = mod / CATALOG_REL
    hooks = mod / HOOKS_REL
    problems: list[str] = []
    if not catalog.exists() or not hooks.exists():
        return [f"{mod.name}: missing catalog or arc hooks"]

    goals = set(GOAL_RE.findall(catalog.read_text(encoding="utf-8")))
    justify = set(JUSTIFY_RE.findall(hooks.read_text(encoding="utf-8")))
    pairs = forward_pairs(catalog)

    for name, labels in (("sc_goal", goals), ("sc_justify", justify)):
        upper = sorted(x for x in labels if x != x.lower())
        if upper:
            problems.append(f"{mod.name}: {name} labels with uppercase: {upper}")
    for label in sorted(goals | justify):
        if re.search(r"(?:^|_)rou(?:_|$)", label):
            problems.append(f"{mod.name}: label uses the non-existent tag ROU: {label}")

    for label in sorted(pairs - goals):
        problems.append(f"{mod.name}: forward pair missing from sc_goal: {label}")
    for label in sorted(pairs - justify):
        problems.append(f"{mod.name}: forward pair missing from sc_justify: {label}")

    # A sc_goal-only label must be the reverse of a forward pair.
    for label in sorted(goals - justify):
        a, _, b = label.partition("_on_")
        if f"{b}_on_{a}" not in pairs:
            problems.append(f"{mod.name}: sc_goal-only label is not a reverse pair: {label}")

    print(f"{mod.name}: {len(goals)} sc_goal, {len(justify)} sc_justify, "
          f"{len(pairs)} forward pairs")
    return problems


def main() -> None:
    mods = [Path(a) for a in sys.argv[1:]] or DEFAULT_MODS
    problems: list[str] = []
    for mod in mods:
        problems += check(mod)
    if problems:
        print()
        for p in problems:
            print(f"FAIL {p}")
        raise SystemExit(1)
    print("\nOK: sc_goal and sc_justify labels agree in every mod")


if __name__ == "__main__":
    main()
